service:
  name: aws-typescript-rest-api

frameworkVersion: '2.0.0'

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt.stage, 'api'}
  region: ${opt.region, 'us-east-1'}
  timeout: 30
  memorySize: 1024
  package:
    excludeDevDependencies: true
    exclude:
      - .git/**
      - .vscode/**

functions:
  app: 
    handler: handler.run
    memorySize: 1024
    description: Lambda function for Typescript REST API
  events:
    - http:
        path: /v1/health
        method: get
    - http:
        path: /v1/candidate/{uniqueId}
        method: get
    - http:
        path: /v1/candidate/{uniqueId}
        method: get
    - http:
        path: /v1/candidate
        method: post
    - http:
        path: /v1/candidates
        method: get
    - http:
        path: /v1/candidate/{uniqueId}
        method: delete
    - http:
        path: /v1/candidate
        method: put
plugins:
- serverless-offline
- serverless-plugin-typescript
